FROM nginx:1.27-alpine

COPY docker/nginx/default.conf /etc/nginx/conf.d/default.conf
COPY index.html /usr/share/nginx/html/index.html
COPY *.js /usr/share/nginx/html/
COPY *.css /usr/share/nginx/html/
